### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by jrchamp** [robstradling/pkct#1]
There was a reference to this proposal here: https://koen.io/2019/01/17/a-tale-of-private-key-reuse/

I followed the IETF Draft link, but the page came up as a 404.

I would like to know more, but I'm sure you're busy so I understand if I'm asking for too much. Thank you for starting the conversation!

**Comment by robstradling** [comment]
@jrchamp Hi.  Thanks for your interest.  I'm afraid that that brief proposal is all that exists right now.
